# SPDX-License-Identifier: GPL-3.0-or-later
# Must run before project(): vcpkg installs the selected manifest here.
set(LFS_BUILD_PROFILE studio CACHE STRING "Build profile: studio or train")
set_property(CACHE LFS_BUILD_PROFILE PROPERTY STRINGS studio train)
if(NOT LFS_BUILD_PROFILE MATCHES "^(studio|train)$")
    message(FATAL_ERROR "LFS_BUILD_PROFILE must be studio or train")
endif()
if(DEFINED LFS_CONFIGURED_BUILD_PROFILE AND
   NOT LFS_CONFIGURED_BUILD_PROFILE STREQUAL LFS_BUILD_PROFILE)
    message(FATAL_ERROR "Use a new build directory when changing LFS_BUILD_PROFILE")
endif()
set(LFS_CONFIGURED_BUILD_PROFILE "${LFS_BUILD_PROFILE}" CACHE INTERNAL "Configured profile")
option(LFS_TRAIN_PYTHON_LOSS "Enable the standalone Python loss bridge (not implemented)" OFF)
option(LFS_TRAIN_PREPROCESS "Enable automatic prior generation in lfs-train (not implemented)" OFF)
set(LFS_TRAIN_ONLY OFF)
list(REMOVE_ITEM VCPKG_MANIFEST_FEATURES studio)
if(LFS_BUILD_PROFILE STREQUAL "train")
    set(LFS_TRAIN_ONLY ON)
    list(REMOVE_ITEM VCPKG_MANIFEST_FEATURES vulkan-validation)
    if(LFS_TRAIN_PYTHON_LOSS OR LFS_TRAIN_PREPROCESS)
        message(FATAL_ERROR "Standalone Python loss and preprocessing are not implemented; use OFF")
    endif()
    set(VCPKG_MANIFEST_NO_DEFAULT_FEATURES ON)
    set(LFS_ENABLE_VULKAN_VALIDATION OFF)
    set(LFS_ENABLE_VULKAN_SHADER_DEBUG_INFO OFF)
    set(LFS_DEV_IMPORT_SOURCE_PYTHON OFF)
    set(LFS_DEV_IMPORT_SOURCE_RESOURCES OFF)
    add_compile_definitions(LFS_TRAIN_ONLY=1)
else()
    list(APPEND VCPKG_MANIFEST_FEATURES studio)
endif()
