# SPDX-License-Identifier: GPL-3.0-or-later
find_package(TBB REQUIRED)
find_package(Threads REQUIRED)
find_package(glm REQUIRED)
find_package(nlohmann_json REQUIRED)
find_package(args REQUIRED)
find_package(fmt CONFIG REQUIRED)
find_package(JPEG REQUIRED)
find_package(PNG REQUIRED)
find_package(TIFF REQUIRED)
find_package(spdlog REQUIRED)
find_package(WebP REQUIRED)
find_package(tinyexr CONFIG REQUIRED)
find_package(zstd CONFIG REQUIRED)
find_package(xxHash CONFIG REQUIRED)
find_package(ZLIB REQUIRED)
